version: '3.7'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  stats:
    build:
      context: ./back
      target: prod
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
      - "3500:3500"
    depends_on:
      - db
  front:
    build: 
      context: ./front
      target: static
    ports: 
      - "3000:3000"

  # The Redis image will run on the sandbox network

networks:
  default:
      external:
          name: sandbox_default
    