version: '3'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  stats:
    build: ./back
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back:/app
    ports:
      - "8000:8000"
      - "3500:3500"
    depends_on:
      - db

  front:
    build: ./front
    command: npm start
    volumes:
      - ./front:/app
    ports: 
      - "3000:3000"

  # The Redis image will run on the sandbox network

networks:
  default:
      external:
          name: sandbox_default
    